apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sngldsdao-website
  labels:
    app: {{ .Values.app.name }}
    component: {{ .Values.app.component }}
    environment: {{ .Values.environment }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.app.domain }}
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Content-Type-Options: nosniff";
      more_set_headers "X-Download-Options: noopen";
      more_set_headers "X-Frame-Options: DENY";
      more_set_headers "X-XSS-Protection: 1; mode=block";

spec:
  tls:
    - hosts:
      - {{ .Values.app.domain }}
      secretName: {{ .Values.app.domain }}
  rules:
    - host: {{ .Values.app.domain }}
      http:
        paths:
          - path: /
            backend:
              serviceName: snglsdao-website
              servicePort: http
